/*
  * Modified by: mercadk
  * Last updated: Jul 7, 2020 10:55:54 AM
  */
package com.caista.birapps.etis.domain.sysad.enums;

public enum MaintenanceTypeEnum {

	ACCREDITED_PRINTER, ADJUSTMENT_CLASSIFICATION, CASE_EVENT_GROUP_DETAIL, TAS_ADJUSTMENT_REASON, ALPHANUMERIC_TAX_CODE, APPLICATION_TYPE, ATTACHMENT_TYPE, AUTHORISATION_TYPE, BANK, BARANGAY, BOOK_OF_ACCOUNT, CASE_EVENT, CASE_TYPE, CITY_MUNICIPALITY, COUNTRY, FORM_TYPE, IDENTIFIER_TYPE, INCENTIVE_CLASSIFICATION, INCENTIVE_GRANTED, INCENTIVE_LEGAL_BASIS, INCENTIVE_TYPE, INDUSTRY_CLASSIFICATION, INDUSTRY_GROUP, OCCUPATION_CLASSIFICATION, OFFICE_CLASS_TYPE, PROVINCE, PSIC_CLASSIFICATION, PSIC_GROUP, PURPOSE_OF_TIN, REASON, REASON_CATEGORY, RECEIPT_INVOICE, REGION, REGULATORY_BODY, RELATIONSHIP_TYPE, REPORT_LIST, SPECIAL_CODE, STATUS, TASK, TASK_EMAIL_GROUP, TAX_FORM_TYPE, TAXPAYER_TYPE, TAX_TYPE, TITLE, ZIPCODE, OFFICE_DIVISION, OFFICE_SERVICE, OFFICE_SECTION, CASE_AGING, CMS_TAX_TYPE, OFFICE_DESIGNATION

}
