/*
  * Modified by: obregoj
  * Last updated: 07 23, 20 11:48:03 AM
  */

package com.caista.birapps.etis.common.utils.module;

public enum EtisSubmodules {

  // NONE
  NONE("NONE"),

  // SYSTEM ADMINISTRATION
  REFERENCE("REFERENCE"), MAINTENANCE("MAINTENANCE"), MANAGE_OFFICE(
      "MANAGE OFFICE"), MANAGE_CASE_OUTLINE("MANAGE CASE OUTLINE"), MANAGE_USER_ASSIGNMENT(
          "MANAGE USER ASSIGNMENT"), UPLOAD_USER_SIGNATURE(
              "UPLOAD USER SIGNATURE"), MANAGE_USER_SIGNATURE(
                  "MANAGE USER SIGNATURE"), MANAGE_SIGNATORY(
                      "MANAGE SIGNATORY"), SUPPORTING_ATTACHMENTS(
                          "SUPPORTING ATTACHMENTS"), ACTIVITY_LOG("ACTIVITY LOG"),

  // KEYCLOAK IDM
  KEYCLOAK_USER_MANAGEMENT("KEYCLOAK USER MANAGEMENT"), KEYCLOAK_USER_ACTIVITY(
      "KEYCLOAK USER ACTIVITY"), KEYCLOAK_REALM_ROLE_MANAGEMENT("KEYCLOAK REALM/ROLE MANAGEMENT"),

  // TASK MANAGER
  CREATE_TASK("CREATE TASK"), ACQUIRE_TASK("ACQUIRE TASK"), APPROVE_TASK(
      "APPROVE TASK"), REJECT_TASK("REJECT TASK"), RELEASE_TASK("RELEASE TASK"),

  // TAXPAYER REGISTRATION SYSTEM
  REGISTER_INDIVIDUAL("REGISTER INDIVIDUAL"), REGISTER_NON_INDIVIDUAL(
      "REGISTER NON-INDIVIDUAL"), REGISTER_FACILITY(
          "REGISTER FACILITY"), REGISTER_BRANCH("REGISTER BRANCH"),

  // TAXPAYER
  MANAGE_FINANCIAL_DETAIL("MANAGE FINANCIAL DETAIL"), TRANSFER_TAXPAYER(
      "TRANSFER TAXPAYER"), TRANSFER_TAXPAYER_BUSINESS(
          "TRANSFER TAXPAYER BUSINESS"), TRANSFER_TAXPAYER_NON_BUSINESS(
              "TRANSFER TAXPAYER NON BUSINESS"), TAG_UNTAG_TAXPAYER(
                  "TAG UNTAG TAXPAYER"), REACTIVATE_TAX_FORM_TYPES(
                      "REACTIVATE TAX AND/OR FORM TYPES"), SUSPEND_TAX_FORM_TYPES(
                          "SUSPEND TAX AND/OR FORM TYPES"), DEREGISTER_TAXPAYER_TAX_FORM_TYPES(
                              "DEREGISTER TAXPAYER TAX AND/OR FORM TYPES"), REACTIVATE_DEREGISTERED_TAXPAYER(
                                  "REACTIVATE DEREGISTERED TAXPAYER"), REREGISTER_TAX_FORM_TYPES(
                                      "REREGISTER TAX AND/OR FORM TYPES"), UPDATE_TAXPAYER(
                                          "UPDATE TAXPAYER"),

  // ATP
  ATP_CREATE("CREATE ATP"), ATP_UPDATE("UPDATE ATP"), ATP_CANCEL("CANCEL ATP"),

  // REPORT
  CERTIFICATE_OF_REGISTRATION("CERTIFICATE OF REGISTRATION"), AUTHORITY_TO_PRINT(
      "AUTHORITY TO PRINT"), CERTIFICATE_OF_REGISTRATION_OF_FACILITY(
          "CERTIFICATE OF REGISTRATION OF FACILITY"), TAX_CLEARANCE_CERTIFICATE(
              "TAX CLEARANCE CERTIFICATE"), TIN_CARD_BATCH_PRINT(
                  "TIN CARD - BATCH PRINT"), BATCH_REPORT("BATCH REPORT"), ACTIVITY_LOG_REPORT(
                      "ACTIVITY LOG REPORT"), FORM_OPERATION_CODE(
                          "FORM OPERATION CODE"), LIST_OF_IRIS_USERS(
                              "LIST OF IRIS USERS"), OFFICE_LIST("OFFICE LIST"),
  // RFP
  RETURN_INQUIRY("RETURN INQUIRY"), RETURN_REVERSAL("RETURN REVERSAL"), RETURN_ADJUSTMENT(
      "RETURN ADJUSTMENT"), RESOLVE_SUSPENDED_RETURNS(
          "RESOLVE SUSPENDED RETURNS"), REPORTS("REPORTS"),
  // CRR
  RECEIVE_PAYMENT("RECEIVE PAYMENT"), MANAGE_PAYMENT("MANAGE PAYMENT"), MANAGE_DISHONORED_CHECK(
      "MANAGE DISHONORED CHECK"), MANAGE_CRDC("MANAGE CRDC"), MANAGE_BSP_LOR(
          "MANAGE BSP-LOR RECORD"), MANAGE_BTR("MANAGE BTR"), MANAGE_DEPOSIT_SLIP(
              "MANAGE DEPOSIT SLIP"), MANAGE_IBCL_RATE(
                  "MANAGE IBCL RATE"), COLLECTION_ACCOUNTABILITY(
                      "COLLECTION ACCOUNTABILITY"), MANAGE_RCO(
                          "MANAGE RCO"), MANAGE_AAB("MANAGE AAB"), FIND_CRDC("FIND_CRDC"),

  // TCR
  MANAGE_APPLICATION("MANAGE APPLICATION"), PROCESS_CLAIM("PROCESS CLAIM"), MANAGE_CASH_REFUND(
      "MANAGE CASH REFUND"), MANAGE_TCC("MANAGE TCC"), MANAGE_TDM("MANAGE TDM"),

  // TCS
  ADD_LEGISLATIVE_DUE_DATE("ADD LEGISLATIVE DUE DATE"), UPDATE_LEGISLATIVE_DUE_DATE(
      "UPDATE LEGISLATIVE DUE DATE"),

  // PENALTY CONFIGURATION
  ADD_PENALTY_CONFIGURATION("ADD_COMPLIANCE_CONFIGURATION"), UPDATE_PENALTY_CONFIGURATION(
      "UPDATE_COMPLIANCE_CONFIGURATION"), VIEW_PENALTY_CONFIGURATION(
          "VIEW_COMPLIANCE_CONFIGURATION"),

  // COMPLIANCE CONFIGURATION
  ADD_COMPLIANCE_CONFIGURATION("ADD_COMPLIANCE_CONFIGURATION"), UPDATE_COMPLIANCE_CONFIGURATION(
      "UPDATE_COMPLIANCE_CONFIGURATION"), VIEW_COMPLIANCE_CONFIGURATION(
          "VIEW_COMPLIANCE_CONFIGURATION"),

  // TAMP MANAGEMENT
  ADD_TAMP_OFFICER("ADD_TAMP_OFFICER"), UPDATE_TAMP_OFFICER("UPDATE_TAMP_OFFICER"), TAMP_DELISTING(
      "TAMP_DELISTING"),

  // HOLIDAY
  ADD_HOLIDAY("ADD HOLIDAY"), UPDATE_HOLIDAY("UPDATE HOLIDAY"),

  // TAS
  ACCOUNT_ADJUSTMENT("ACCOUNT ADJUSTMENT"), UPDATE_ACCOUNT_ADJUSTMENT(
      "UPDATE ACCOUNT ADJUSTMENT"), TRANSFER_PAYMENT_CREDIT(
          "TRANSFER PAYMENT CREDIT"), UPDATE_TRANSFER_PAYMENT_CREDIT(
              "UPDATE TRANSFER PAYMENT CREDIT"),

  // CMS
  CASE("CASE"), AUDIT_CREATE_MANUAL_CASE("AUDIT CREATE MANUAL CASE"), AUDIT_MANAGE_CASE(
      "AUDIT MANAGE CASE"), AUDIT_MANAGE_0500_SERIES(
          "AUDIT MANAGE 0500 SERIES"), AUDIT_MANAGE_COLLECTION_REPORT(
              "AUDIT MANAGE COLLECTION REPORT"), CMS_REPORTS("CMS REPORTS"),

  // CMS REPORTS
  AUDIT_INVESTIGATING_OFFICES("AUDIT INVESTIGATING OFFICES"), AUDIT_REVIEWING_OFFICES(
      "AUDIT REVIEWING OFFICES"), AUDIT_CASE_TRANSFERRED_PENDING_ACCEPTANCE(
          "AUDIT CASE TRANSFERRED PENDING ACCEPTANCE"), AUDIT_CASE_LIST_OF_EMOA_ASSIGNED_TO_ORIG_GS(
              "AUDIT LIST OF EMOAS ASSIGNED TO THE ORIGINAL GROUP SUPERVISOR (GS)"), AUDIT_CASE_STATUS_OF_LA_TVN(
                  "AUDIT STATUS OF LETTER OF AUTHORITY/TAX VERIFICATION NOTICE"),

  // CMS CORRESPONDENCE
  AUDIT_ASSESSMENT_NOTICE(
      "AUDIT ASSESSMENT NOTICE"), AUDIT_AUTHORITY_TO_ISSUE_REFUND_TAX_CREDIT_CERT(
          "AUDIT AUTHORITY TO ISSUE REFUND TAX CREDIT CERTIFICATE"), AUDIT_DENIAL_LETTER(
              "AUDIT DENIAL LETTER"), AUDIT_FINAL_ASSESSMENT_NOTICE(
                  "AUDIT FINAL ASSESSMENT NOTICE"), AUDIT_FINAL_DECISION_ON_DISPUTED_ASSESSMENT(
                      "AUDIT FINAL DECISION ON DISPUTED ASSESSMENT"), AUDIT_FINAL_NOTICE(
                          "AUDIT FINAL NOTICE FOR PRESENTATION OF RECORDS AND/OR DOCUMENTS"), AUDIT_FIRST_NOTICE(
                              "AUDIT CHECKLIST OF REQUIREMENTS AND FIRST REQUEST FOR PRESENTATION OF RECORDS"), AUDIT_LETTER_OF_AUTHORITY_TAX_FRAUD(
                                  "AUDIT LETTER OF AUTHORITY - TAX FRAUD"), AUDIT_LETTER_OF_AUTHORITY(
                                      "AUDIT LETTER OF AUTHORITY"), AUDIT_MEMORANDUM_ASSIGNMENT(
                                          "AUDIT MEMORANDUM ASSIGNMENT"), AUDIT_NOTICE_OF_INFORMAL_CONFERENCE(
                                              "AUDIT NOTICE OF INFORMAL CONFERENCE"), AUDIT_NOTICE_OF_INFORMAL_CONFERENCE_VATAS(
                                                  "AUDIT NOTICE OF INFORMAL CONFERENCE VATAS"), AUDIT_PRELIMINARY_ASSESSMENT_NOTICE_II(
                                                      "AUDIT PRELIMINARY ASSESSMENT NOTICE II"), AUDIT_PRELIMINARY_ASSESSMENT_NOTICE(
                                                          "AUDIT PRELIMINARY ASSESSMENT NOTICE"), AUDIT_REFUND_NOTICE_APPROVED_WITH_IMPORTATIONS(
                                                              "AUDIT REFUND NOTICE - APPROVED - WITH IMPORTATIONS"), AUDIT_REFUND_NOTICE_APPROVED(
                                                                  "AUDIT REFUND NOTICE - APPROVED"), AUDIT_REPLACEMENT_LETTER_OF_AUTHORITY(
                                                                      "AUDIT REPLACEMENT LETTER OF AUTHORITY"), AUDIT_SUBPOENA_DUCES_TECUM(
                                                                          "AUDIT SUBPOENA DUCES TECUM"), AUDIT_TAX_VERIFICATION_NOTICE(
                                                                              "AUDIT TAX VERIFICATION NOTICE"), AUDIT_LETTER_TO_BOC(
                                                                                  "AUDIT LETTER TO BOC"), AUDIT_AGREEMENT_FORM(
                                                                                      "AUDIT AGREEMENT FORM"), AUDIT_TERMINATION_LETTER(
                                                                                          "AUDIT TERMINATION LETTER"), AUDIT_FORM_0500_SERIES(
                                                                                              "AUDIT FORM 0500 SERIES"), AUDIT_COLLECTION_REPORT(
                                                                                                  "AUDIT COLLECTION REPORT"),

  NON_AUDIT_REMINDER_LETTER("NON-AUDIT REMINDER LETTER"), NON_AUDIT_NOTICE_FOR_TAX_COMPLIANCE(
      "NON-AUDIT NOTICE FOR TAX COMPLIANCE"), NON_AUDIT_PCC_CORRESPONDENCE(
          "NON_AUDIT_PCC_CORRESPONDENCE"), NON_AUDIT_PENDING_CASES(
              "NON-AUDIT PENDING CASES"), FILSUB_CASE_NOTES(
                  "FILING/SUBMISSION COMPLIANCE CASE NOTES"), PAYMENT_CASE_NOTES(
                      "PAYMENT COMPLIANCE CASE NOTES"),

  CASE_NOTES("CASE NOTES"),

  // AUDIT SELECTION SYSTEM
  FETCH_SELECTION_CRITERIAS("FETCH SELECTION CRITERIAS"), CREATE_SELECTION_CRITERIA(
      "CREATE SELECTION CRITERIA"), UPDATE_SELECTION_CRITERIA(
          "UPDATE SELECTION CRITERIA"), CREATE_AUDIT_PROGRAM(
              "CREATE AUDIT PROGRAM"), UPDATE_AUDIT_PROGRAM(
                  "UPDATE AUDIT PROGRAM"), SIMULATE_AUDIT_PROGRAM(
                      "SIMULATE AUDIT PROGRAM"), EXECUTE_AUDIT_PROGRAM(
                          "EXECUTE AUDIT PROGRAM"), SUBMIT_TAXPAYER_AUDIT(
                              "SUBMIT_TAXPAYER_AUDIT"), SAVE_SELECTION_CRITERIA(
                                  "SAVE SELECTION CRITERIA"), FETCH_AUDIT_PROGRAMS(
                                      "FETCH AUDIT PROGRAMS"), SAVE_AUDIT_PROGRAM(
                                          "SAVE AUDIT PROGRAM"), FETCH_SIMULATE_PROGRAM_REPORT(
                                              "FETCH SIMULATE PROGRAM REPORT"), FETCH_ACTUAL_PROGRAM_REPORT(
                                                  "FETCH ACTUAL PROGRAM REPORT"), UPDATE_ACTUAL_PROGRAM_REPORT(
                                                      "UPDATE ACTUAL PROGRAM REPORT"), CREATE_REFERENCE(
                                                          "CREATE REFERENCE"), UPDATE_REFERENCE(
                                                              "UPDATE REFERENCE"),

  // BATCH
  UPDATE_SCHEDULE("STATUS OR SCHEDULE UPDATE");

  private String description;

  private EtisSubmodules(String description) {
    this.description = description;
  }

  public String getDescription() {
    return this.description;
  }

}
