/*
  * Modified by: obregoj
  * Last updated: 07 23, 20 2:31:37 PM
  */

package com.caista.birapps.etis.domain.audit.entity.constant;

public enum LogEvent {
  // DEFAULT
  NONE("NONE"),

  // COMMON
  CREATE("CREATE"), UPDATE("UPDATE"), INVALIDATE("INVALIDATE"), DELETE("DELETE"), VIEW("VIEW"),

  // KEYCLOAK
  CREATE_ROLE("CREATE ROLE"), DELETE_ROLE("DELETE ROLE"), CREATE_GROUP(
      "CREATE GROUP"), DELETE_GROUP("DELETE GROUP"), CREDENTIAL_UPDATE(
          "CREDENTIAL UPDATE"), INVALIDATE_SESSION(
              "INVALIDATE SESSION"), LOGIN("LOGIN"), LOGIN_FAILED("LOGIN FAILED"), LOGOUT("LOGOUT"),

  // TASK MANAGER
  CREATE_TASK("CREATE TASK"), ACQUIRE_TASK("ACQUIRE TASK"), APPROVE_TASK(
      "APPROVE TASK"), RELEASE_TASK("RELEASE TASK"), REJECT_TASK("REJECT TASK"),

  // TAXPAYER
  MANGE_FINANCIAL_DETAIL("MANGE FINANCIAL DETAIL"), TRANSFER_TAXPAYER(
      "TRANSFER TAXPAYER"), TRANSFER_TAXPAYER_BUSINESS(
          "TRANSFER TAXPAYER BUSINESS"), TRANSFER_TAXPAYER_NON_BUSINESS(
              "TRANSFER TAXPAYER NON BUSINESS"), TAG_UNTAG_TAXPAYER(
                  "TAG UNTAG TAXPAYER"), DEREGISTER_TAXPAYER_TAX_FORM_TYPES(
                      "DEREGISTER TAXPAYER TAX AND/OR FORM TYPES"), REACTIVATE_DEREGISTERED_TAXPAYER(
                          "REACTIVATE DEREGISTERED TAXPAYER"), SUSPEND_TAX_FORM_TYPES(
                              "SUSPEND TAX AND/OR FORM TYPES"), REACTIVATE_TAX_FORM_TYPES(
                                  "REACTIVATE TAX AND/OR FORM TYPES"), REREGISTER_TAX_FORM_TYPES(
                                      "REREGISTER TAX AND/OR FORM TYPES"), UPDATE_TAXPAYER(
                                          "UPDATE TAXPAYER"),

  // ATP
  ATP_CREATE("CREATE ATP"), ATP_UPDATE("UPDATE ATP"), ATP_CANCEL("CANCEL ATP"),

  // TRS
  REGISTER_INDIVIDUAL("REGISTER INDIVIDUAL"), REGISTER_NONDIVIDUAL(
      "REGISTER NONDIVIDUAL"), REGISTER_BRANCH(
          "REGISTER BRANCH"), REGISTER_FACILITY("REGISTER FACILITY"),

  // REPORT
  GENERATE_CERTIFICATE_OF_REGISTRATION(
      "GENERATE CERTIFICATE OF REGISTRATION"), PRINT_CERTIFICATE_OF_REGISTRATION(
          "PRINT CERTIFICATE OF REGISTRATION"), GENERATE_AUTHORITY_TO_PRINT(
              "GENERATE AUTHORITY TO PRINT"), PRINT_AUTHORITY_TO_PRINT(
                  "PRINT AUTHORITY TO PRINT"), GENERATE_CERTIFICATE_OF_REGISTRATION_OF_FACILITY(
                      "GENERATE CERTIFICATE OF REGISTRATION OF FACILITY"), PRINT_CERTIFICATE_OF_REGISTRATION_OF_FACILITY(
                          "PRINT CERTIFICATE OF REGISTRATION OF FACILITY"), GENERATE_TAX_CLEARANCE_CERTIFICATE(
                              "GENERATE TAX CLEARANCE CERTIFICATE"), PRINT_TAX_CLEARANCE_CERTIFICATE(
                                  "PRINT TAX CLEARANCE CERTIFICATE"), DOWNLOAD_BATCH_REPORT(
                                      "DOWNLOAD BATCH REPORT"), GENERATE_ACTIVITY_LOG_REPORT(
                                          "GENERATE ACTIVITY LOG REPORT"), GENERATE_FORM_OPERATION_CODE(
                                              "GENERATE FORM OPERATION CODE"), GENERATE_LIST_OF_IRIS_USERS(
                                                  "GENERATE LIST OF IRIS USERS"), GENERATE_OFFICE_LIST(
                                                      "GENERATE OFFICE LIST"), GENERATE_TIN_BATCH_PRINT(
                                                          "GENERATE TIN BATCH PRINT"), GENERATE_CMS_REPORT(
                                                              "GENERATE CMS REPORT"),

  // TCR
  ADD_APPLICATION("ADD APPLICATION"), MODIFY_APPLICATION(
      "MODIFY APPLICATION"), CHANGE_MODE_OF_CLAIM(
          "CHANGE MODE OF CLAIM"), UPDATE_REJECTED_APPLICATION(
              "UPDATE_REJECTED_APPLICATION"), PROCESS_TCC("PROCESS TCC"), TCC_ISSUANCE(
                  "TCC ISSUANCE"), CASH_REFUND_GRANT(
                      "CASH REFUND GRANT"), PROCESS_CASH_REFUND("PROCESS CASH REFUND"), ADD_TCC(
                          "ADD TCC"), MODIFY_TCC("MODIFY TCC"), SUBMIT_REVALIDATE_TCC(
                              "SUBMIT REVALIDATE TCC"), SUBMIT_CONVERT_CASH("SUBMIT CONVERT CASH"),

  SUBMIT_CANCEL_TCC("SUBMIT CANCEL TCC"),

  SUBMIT_REPLACE_TCC("SUBMIT REPLACE TCC"), ADD_TDM("ADD TDM"),

  SUBMIT_TDM_ISSUANCE("SUBMIT TDM ISSUANCE"), SUBMIT_TDM_CANCEL("SUBMIT TDM CANCEL"),

  SUBMIT_TDM_REPLACE("SUBMIT TDM REPLACE"), MODIFY_TDM("MODIFY TDM"),

  // TCS
  ADD_PENALTY("ADD PENALTY"), UPDATE_PENALTY("UPDATE PENALTY"),

  ADD_COMPLIANCE_CONFIGURATION("ADD COMPLIANCE CONFIGURATION"),

  UPDATE_COMPLIANCE_CONFIGURATION("UPDATE COMPLIANCE CONFIGURATION"), ADD_HOLIDAY("ADD HOLIDAY"),

  UPDATE_HOLIDAY("UPDATE HOLIDAY"), ADD_LEGISLATIVE_DUE_DATE("ADD LEGISLATIVE DUE DATE"),

  UPDATE_LEGISLATIVE_DUE_DATE("UPDATE LEGISLATIVE DUE DATE"), ADD_TAMP_OFFICER("ADD TAMP OFFICER"),

  UPDATE_TAMP_OFFICER("UPDATE TAMP OFFICER"), TAMP_DELISTING("TAMP DELISTING"),

  // CRR
  DEPOSIT_SLIP("DEPOSIT_SLIP"), DEACTIVATE("DEACTIVATE"), REACTIVATE("REACTIVATE"), CANCEL(
      "CANCEL"), TAG_DISHONORED_CHECK("TAG DISHONORED CHECK"), UPDATE_DISHONORED_CHECK(
          "UPDATE DISHONORED CHECK"), SAVE_TEMP_BCS("SAVE TEMPORARY BCS"), UPDATE_TEMP_BCS(
              "UPDATE TEMPORARY BCS"), RESOLVE_SUSPENDED_PAYMENT(
                  "RESOLVE SUSPENDED PAYMENT"), APPROVE_CANCEL("APPROVE CANCEL"), SAVE_TEMP_BSP(
                      "SAVE BSP TEMP"), UPDATE_TEMP_BSP("UPDATE BSP TEMP"), SAVE_IBCL(
                          "SAVE IBCL"), APPROVE_UPDATE_DISHONORED_CHECK(
                              "APPROVE UPDATE DISHONORED CHECK"), REJECT_UPDATE_DISHONORED_CHECK(
                                  "REJECT UPDATE DISHONORED CHECK"), APPROVE_UPDATE_CRDC(
                                      "APPROVE UPDATE CRDC"), REJECT_UPDATE_CRDC(
                                          "REJECT UPDATE CRDC"), APPROVE_DELETE_CRDC(
                                              "APPROVE DELETE CRDC"), REJECT_DELETE_CRDC(
                                                  "REJECT DELETE CRDC"), APPROVE_DEPOSIT_SLIP(
                                                      "APPROVE DEPOSIT SLIP"), REJECT_DEPOSIT_SLIP(
                                                          "REJECT DEPOSIT SLIP"), APPROVE_IBCL_RATE(
                                                              "APPROVE IBCL RATE"), REJECT_IBCL_RATE(
                                                                  "REJECT IBCL RATE"), APPROVE_RCO(
                                                                      "APPROVE RCO"), REJECT_RCO(
                                                                          "REJECT RCO"), APPROVE_DEACTIVATE_RCO(
                                                                              "APPROVE DEACTIVATE RCO"), REJECT_DEACTIVATE_RCO(
                                                                                  "REJECT DEACTIVATE RCO"), APPROVE_REACTIVATE_RCO(
                                                                                      "APPROVE REACTIVATE RCO"), REJECT_REACTIVATE_RCO(
                                                                                          "REJECT REACTIVATE RCO"), APPROVE_REACTIVATE_AAB(
                                                                                              "APPROVE REACTIVATE AAB"), REJECT_REACTIVATE_AAB(
                                                                                                  "REJECT REACTIVATE AAB"), APPROVE_DEACTIVATE_AAB(
                                                                                                      "APPROVE DEACTIVATE AAB"), REJECT_DEACTIVATE_AAB(
                                                                                                          "REJECT DEACTIVATE AAB"),

  // PUDS-MONITORING
  SEND_SCHEDULE("SEND SCHEDULE"),

  // TAS
  ACCOUNT_ADJUSTMENT("ACCOUNT ADJUSTMENT"), UPDATE_ACCOUNT_ADJUSTMENT(
      "UPDATE ACCOUNT ADJUSTMENT"), TRANSFER_PAYMENT_CREDIT(
          "TRANSFER PAYMENT CREDIT"), UPDATE_TRANSFER_PAYMENT_CREDIT(
              "UPDATE TRANSFER PAYMENT CREDIT"), SUBMIT_ACCOUNT_ADJUSTMENT(
                  "SUBMIT ACCOUNT ADJUSTMENT"), SUBMIT_TRANSFER_PAYMENT_CREDIT(
                      "SUBMIT TRANSFER PAYMENT/CREDIT"),

  // CMS
  AUDIT_CREATE_MANUAL_CASE("AUDIT CREATE MANUAL CASE"), AUDIT_MANAGE_CASE(
      "AUDIT MANAGE CASE"), AUDIT_SAVE_0500_SERIES(
          "AUDIT SAVE 0500 SERIES"), AUDIT_CANCEL_0500_SERIES(
              "AUDIT CANCEL 0500 SERIES"), AUDIT_SAVE_COLLECTION_REPORT(
                  "AUDIT SAVE COLLECTION REPORT"), AUDIT_UPDATE_COLLECTION_REPORT(
                      "AUDIT UPDATE COLLECTION REPORT"),

  // CMS USER REPORTS
  GENERATE_CMS_AUDIT_INVESTIGATING_OFFICES("GENERATE AUDIT INVESTIGATING OFFICES"),

  GENERATE_CMS_AUDIT_REVIEWING_OFFICES("GENERATE AUDIT REVIEWING OFFICES"),

  GENERATE_CMS_AUDIT_CASE_TRANSFERRED_PENDING_ACCEPTANCE(
      "GENERATE AUDIT TRANSFERRED PENDING ACCEPTANCE"),

  GENERATE_CMS_AUDIT_CASE_LIST_OF_EMOA_ASSIGNED_TO_ORIG_GS(
      "GENERATE AUDIT LIST OF EMOAS ASSIGNED TO THE ORIGINAL GROUP SUPERVISOR (GS)"),

  GENERATE_CMS_AUDIT_CASE_STATUS_OF_LA_TVN(
      "GENERATE AUDIT STATUS OF LETTER OF AUTHORITY/TAX VERIFICATION NOTICE"),

  GENERATE_CMS_NON_AUDIT_PENDING_CASES("GENERATE CMS NON-AUDIT PENDING CASES"),

  // CMS CORRESPONDENCE
  GENERATE_CMS_AUDIT_ASSESSMENT_COLLECTION_REPORT("GENERATE AUDIT ASSESSMENT COLLECTION REPORT"),

  GENERATE_CMS_AUDIT_ASSESSMENT_NOTICE("GENERATE AUDIT ASSESSMENT NOTICE"),

  GENERATE_CMS_AUDIT_AUTHORITY_TO_ISSUE_REFUND_TAX_CREDIT_CERT(
      "GENERATE AUDIT AUTHORITY TO ISSUE REFUND TAX CREDIT CERTIFICATE"),

  GENERATE_CMS_AUDIT_DENIAL_LETTER("GENERATE AUDIT DENIAL LETTER"),

  GENERATE_CMS_AUDIT_FINAL_ASSESSMENT_NOTICE("GENERATE AUDIT FINAL ASSESSMENT NOTICE"),

  GENERATE_CMS_AUDIT_FINAL_DECISION_ON_DISPUTED_ASSESSMENT(
      "GENERATE AUDIT FINAL DECISION ON DISPUTED ASSESSMENT"),

  GENERATE_CMS_AUDIT_FINAL_NOTICE(
      "GENERATE AUDIT FINAL NOTICE FOR PRESENTATION OF RECORDS AND/OR DOCUMENTS"),

  GENERATE_CMS_AUDIT_FIRST_NOTICE(
      "GENERATE AUDIT CHECKLIST OF REQUIREMENTS AND FIRST REQUEST FOR PRESENTATION OF RECORDS"),

  GENERATE_CMS_AUDIT_LETTER_OF_AUTHORITY_TAX_FRAUD(
      "GENERATE AUDIT LETTER OF AUTHORITY - TAX FRAUD"),

  GENERATE_CMS_AUDIT_LETTER_OF_AUTHORITY("GENERATE AUDIT LETTER OF AUTHORITY"),

  GENERATE_CMS_AUDIT_MEMORANDUM_ASSIGNMENT("GENERATE AUDIT MEMORANDUM ASSIGNMENT"),

  GENERATE_CMS_AUDIT_NOTICE_OF_INFORMAL_CONFERENCE("GENERATE AUDIT NOTICE OF INFORMAL CONFERENCE"),

  GENERATE_CMS_AUDIT_NOTICE_OF_INFORMAL_CONFERENCE_VATAS(
      "GENERATE AUDIT NOTICE OF INFORMAL CONFERENCE VATAS"),

  GENERATE_CMS_AUDIT_PRELIMINARY_ASSESSMENT_NOTICE_II(
      "GENERATE AUDIT PRELIMINARY ASSESSMENT NOTICE II"),

  GENERATE_CMS_AUDIT_PRELIMINARY_ASSESSMENT_NOTICE("GENERATE AUDIT PRELIMINARY ASSESSMENT NOTICE"),

  GENERATE_CMS_AUDIT_REFUND_NOTICE_APPROVED_WITH_IMPORTATIONS(
      "GENERATE REFUND NOTICE - APPROVED - WITH IMPORTATIONS"),

  GENERATE_CMS_AUDIT_REFUND_NOTICE_APPROVED("GENERATE AUDIT REFUND NOTICE - APPROVED"),

  GENERATE_CMS_AUDIT_REPLACEMENT_LETTER_OF_AUTHORITY(
      "GENERATE AUDIT REPLACEMENT LETTER OF AUTHORITY"),

  GENERATE_CMS_AUDIT_SUBPOENA_DUCES_TECUM("GENERATE AUDIT SUBPOENA DUCES TECUM"),

  GENERATE_CMS_AUDIT_TAX_VERIFICATION_NOTICE("GENERATE AUDIT TAX VERIFICATION NOTICE"), CASE_NOTES(
      "CASE_NOTES"),

  GENERATE_CMS_AUDIT_LETTER_TO_BOC("GENERATE CMS AUDIT LETTER TO BOC"),

  GENERATE_CMS_AUDIT_AGREEMENT_FORM("GENERATE CMS AUDIT AGREEMENT FORM"),

  GENERATE_CMS_AUDIT_TERMINATION_LETTER("GENERATE CMS AUDIT TERMINATION LETTER"),

  GENERATE_CMS_AUDIT_FORM_0500_SERIES("GENERATE CMS AUDIT FORM 0500 SERIES"),

  GENERATE_CMS_AUDIT_COLLECTION_REPORT("GENERATE CMS AUDIT COLLECTION REPORT"),

  GENERATE_CMS_NON_AUDIT_REMINDER_LETTER("GENERATE CMS NON-AUDIT REMINDER LETTER"),

  GENERATE_CMS_NON_AUDIT_NOTICE_FOR_TAX_COMPLIANCE(
      "GENERATE CMS NON-AUDIT NOTICE FOR TAX COMPLIANCE"),

  GENERATE_CMS_NON_AUDIT_PCC_CORRESPONDENCE("GENERATE CMS NON-AUDIT PCC CORRESPONDENCE"),

  FILSUB_CASE_NOTES("FILSUB_CASE_NOTES"),

  PAYMENT_CASE_NOTES("PAYMENT_CASE_NOTES"),

  SYSTEM_STARTUP("API HAS BEEN DEPLOYED"),

  // AUDIT SELECTION
  FIND_SELECTION_CRITERIA("FIND SELECTION CRITERIA"), CREATE_SELECTION_CRITERIA(
      "CREATE SELECTION CRITERIA"), UPDATE_SELECTION_CRITERIA(
          "UPDATE SELECTION CRITERIA"), CREATE_AUDIT_PROGRAM(
              "CREATE AUDIT PROGRAM"), UPDATE_AUDIT_PROGRAM(
                  "UPDATE AUDIT PROGRAM"), SIMULATE_AUDIT_PROGRAM(
                      "SIMULATE AUDIT PROGRAM"), EXECUTE_AUDIT_PROGRAM(
                          "EXECUTE AUDIT PROGRAM"), SUBMIT_TAXPAYER_AUDIT(
                              "SUBMIT_TAXPAYER_AUDIT"), FIND_AUDIT_PROGRAM(
                                  "FIND AUDIT PROGRAM"), FIND_SIMULATE_PROGRAM_REPORT(
                                      "FIND SIMULATE PROGRAM REPORT"), CREATE_ACTUAL_PROGRAM_REPORT(
                                          "CREATE ACTUAL PROGRAM REPORT"), UPDATE_ACTUAL_PROGRAM_REPORT(
                                              "UPDATE ACTUAL PROGRAM REPORT");

  private String description;

  private LogEvent(String description) {
    this.description = description;
  }

  public String getDescription() {
    return description;
  }
}
